language: csharp
mono:
- beta
solution: DOTA2.sln
install:
- curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | sh && source ~/.dnx/dnvm/dnvm.sh && dnvm upgrade

script:
- cd ./source/IrcDotNet/ && dnu restore . && dnu build . && cd -
- cd ./test/IrcDotNet.Test/ && dnu restore . && dnu build . && cd -
- mkdir -p .nuget && wget -O .nuget/nuget.exe https://www.nuget.org/nuget.exe && mono .nuget/nuget.exe install NUnit.Runners -Version 2.6.3 -OutputDirectory tools
- mono ./tools/NUnit.Runners.2.6.3/tools/nunit-console.exe ./artifacts/bin/IrcDotNet.Test/Debug/net451/IrcDotNet.Test.dll
