language: csharp
mono:
- beta
solution: DOTA2.sln
install:
- curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | sh && source ~/.dnx/dnvm/dnvm.sh && dnvm upgrade

script:
- mkdir -p artifacts/ .nuget/
- dnu restore source/IrcDotNet/ test/IrcDotNet.Test/
- dnu build source/IrcDotNet/ test/IrcDotNet.Test/
- cd test/IrcDotNet.Test/ && dnx IrcDotNet.Test
