os: Visual Studio 2015
init:
  - git config --global core.autocrlf input
install:
  - dnvm update -r clr
  - dnu restore source/IrcDotNet/ test/IrcDotNet.Test/
build_script:
  - cmd: cd test/IrcDotNet.Test/ && dnu build && dnx IrcDotNet.Test
test: off
version: 0.0.1.{build}
artifacts:
  - path: source/IrcDotNet/bin/Debug
    name: bin
